# -----------------------------------------------------------------------------
# Copyright Helio Chissini de Castro 2022.
# Part of the SW360 Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# -----------------------------------------------------------------------------

name: Docker Build

on:
  schedule:
    - cron: '0 0 * * *' # Midnight
  workflow_dispatch:
    inputs:
      invalidate-cache:
        description: 'Build all images disregarding exists same version'
        required: false
      debug:
        description: 'Debug docker build'
        required: false
  push:
    tags:
      - 'sw360-*'
    paths-ignore:
      - '**.md'

env:
  REGISTRY: ghcr.io

permissions: write-all

jobs:
  sw360_version:
    name: SW360 Version
    runs-on: ubuntu-latest
    outputs:
      sw360_version: ${{ steps.pom_version.outputs.SW360_VERSION }}

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          cache: 'maven'
          distribution: 'temurin'

      - name: Get revision from pom.xml
        id: pom_version
        run: |
          echo "SW360_VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> "$GITHUB_OUTPUT"
  base_image:
    name: SW360 Base image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV
      - name: Build base image
        uses: heliocastro/docker-build-control@main
        with:
          name: base
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.JAVA_VERSION }}-jdk-${{ env.UBUNTU_VERSION }}
          invalidate-cache: ${{ inputs.invalidate-cache }}
          debug: ${{ inputs.debug }}
          build-args: |
            LIFERAY_VERSION=${{ env.LIFERAY_VERSION }}
            LIFERAY_SOURCE=${{ env.LIFERAY_SOURCE }}
            JAVA_VERSION=${{ env.JAVA_VERSION }}
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}

  thrift_image:
    name: Build SW360 Thrift image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV

      - name: Build thrift image
        uses: heliocastro/docker-build-control@main
        with:
          name: thrift
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.THRIFT_VERSION }}
          invalidate-cache: ${{ inputs.invalidate-cache }}
          debug: ${{ inputs.debug }}
          build-args: |
            THRIFT_VERSION=${{ env.THRIFT_VERSION }}
